In [5]:
import tensorflow as tf

/home/jackdaniel/ve/ml/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jackdaniel/ve/ml/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jackdaniel/ve/ml/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jackdaniel/ve/ml/lib/python3.6/site-packages/tensorflow/python/framework/dty

In [9]:
print(tf.__version__)

1.14.0


In [11]:
name1=tf.constant("jack")
name2=tf.constant("daniel")

In [29]:
name3=name1+" "+name2

In [30]:
#session to run the variables
with tf.Session() as sess:
    result=sess.run(name3)

In [31]:
print(result)

b'jack daniel'


In [32]:
#session automatically closed by with key word
with tf.Session() as sess:
    results=sess.run(name1+" "+name2)

In [33]:
results

b'jack daniel'

## operations

In [37]:
#interactive session
sess=tf.InteractiveSession()

In [38]:
num1=tf.constant(10)
num2=tf.constant(20)

In [40]:
sess.run(num1+num2)

30

In [41]:
ones=tf.ones((3,3))

In [42]:
ones.eval()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [51]:
zeros=tf.zeros((3,3))


In [44]:
random=tf.random_normal((3,3))

In [48]:
random_u=tf.random_uniform((3,3),minval=0,maxval=1)

In [52]:
fill=tf.fill((5,5),20)

In [53]:
operation=[num1,num2,ones,zeros,random,random_u]

In [56]:
for op in operation:
    print(sess.run(op))
    print("\n")

10


20


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[-1.4035532  -1.5534887  -0.19040301]
 [ 0.02716276 -0.8460758   1.0254068 ]
 [ 0.48587534  0.4333142  -1.0838362 ]]


[[0.02256715 0.39215076 0.8326658 ]
 [0.18608308 0.9486519  0.684288  ]
 [0.38581038 0.63571215 0.6101568 ]]




## matrix multiplication

In [61]:
mat1=tf.constant([ [1,2,3],
                   [4,5,6] 
                 ])

In [62]:
mat1.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [64]:
mat2=tf.constant([ [7],
                   [10],
                   [11]
                 ])

In [65]:
mat2.get_shape()

TensorShape([Dimension(3), Dimension(1)])

In [70]:
miltiplication=tf.matmul(mat1,mat2)

In [71]:
sess.run(multiplication)

array([[ 60],
       [144]], dtype=int32)